---
- name: "Dirs: Create directories in {{ bsd_named_conf_path }}"
  ansible.builtin.file:
    state: directory
    path: "{{ item.dir }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ bsd_named_conf_dirs }}"
  loop_control:
    label: "{{ item.dir }}"
  tags: bsd_dns_create_named_dirs

- name: "Dirs: Set atributes of {{ bsd_named_conf_log_file }}"
  ansible.builtin.file:
    state: touch
    path: "{{ bsd_named_conf_log_file }}"
    owner: "{{ bsd_named_conf_log_file_owner }}"
    group: "{{ bsd_named_conf_log_file_group }}"
    mode: "{{ bsd_named_conf_log_file_mode }}"
    access_time: preserve
    modification_time: preserve
  when: bsd_named_conf_log | bool
  tags: bsd_dns_create_log

# EOF
