---

- name: "dirs: Create directory for chrooted named {{ bsd_named_chrootdir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_named_chrootdir }}"
    owner: root
    group: wheel
    mode: '0755'
  when: bsd_named_chrootdir is defined
  tags: bsd_dns_create_named_chrootdir

- name: "dirs: Create chrooted directory for keys {{ path }}"
  ansible.builtin.file:
    state: directory
    path: "{{ path }}"
    owner: root
    group: wheel
    mode: '0755'
  vars:
    path: "{{ [bsd_named_chrootdir, bsd_named_conf_keys]|join('/')|replace('//', '/') }}"
  when: bsd_named_chrootdir is defined
  tags: bsd_dns_create_keydir_chrooted

- name: "dirs: Create directory for keys {{ bsd_named_conf_keys }}"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_named_conf_keys }}"
    owner: root
    group: wheel
    mode: '0755'
  tags: bsd_dns_create_keydir

- name: "dirs: Create working directory {{ bsd_named_conf_working }}"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_named_conf_working }}"
    owner: bind
    group: bind
    mode: '0755'
  tags: bsd_dns_create_workingdir

- name: "dirs: Set atributes of {{ bsd_named_conf_log_file }}"
  ansible.builtin.file:
    state: touch
    path: "{{ bsd_named_conf_log_file }}"
    owner: "{{ bsd_named_conf_log_file_owner }}"
    group: "{{ bsd_named_conf_log_file_group }}"
    mode: "{{ bsd_named_conf_log_file_mode }}"
    access_time: preserve
    modification_time: preserve
  when: bsd_named_conf_log|bool
  tags: bsd_dns_create_log

# EOF
...
