---
# tasks freebsd_dns

- import_tasks: sanity.yml
  tags: [bsd_dns_sanity, always]

- import_tasks: debug.yml
  when: bsd_dns_debug|bool
  tags: [bsd_dns_debug, always]

- import_tasks: packages.yml
  when: bsd_dns_install|bool
  tags: bsd_dns_packages

- import_tasks: dirs.yml
  tags: bsd_dns_dirs

- import_tasks: named.yml
  tags: bsd_dns_named

- import_tasks: zones.yml
  tags: bsd_dns_zones

- import_tasks: rcconf.yml
  tags: bsd_dns_rcconf

# EOF
...
