---
# tasks freebsd_dns

- name: Import sanity.yml
  ansible.builtin.import_tasks: sanity.yml
  tags: [bsd_dns_sanity, always]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: bsd_dns_debug|bool
  tags: bsd_dns_debug

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: bsd_dns_install|bool
  tags: bsd_dns_packages

- name: Import dirs.yml
  ansible.builtin.import_tasks: dirs.yml
  tags: bsd_dns_dirs

- name: Import named.yml
  ansible.builtin.import_tasks: named.yml
  tags: bsd_dns_named

- name: Import zones.yml
  ansible.builtin.import_tasks: zones.yml
  tags: bsd_dns_zones

- name: Import rcconf.yml
  ansible.builtin.import_tasks: rcconf.yml
  tags: bsd_dns_rcconf

# EOF
