---
- name: Package(s) not present and installation disabled.
  when: not bsd_dns_install | bool
  block:

    - name: "Sanity: Collect installed packages."
      ansible.builtin.package_facts:

    - name: "Sanity: Set my_missing_packages"
      ansible.builtin.set_fact:
        my_missing_packages: "{{ required_packages | difference(ansible_facts.packages.keys()) }}"
      vars:
        required_packages: "{{ bsd_dns_packages | map('split', '/') | map('last') }}"

    - name: Missing packages
      when: my_missing_packages | length > 0
      block:

        - name: "Sanity: Debug missing packages."
          ansible.builtin.debug:
            msg: >
              [ERR] Packages {{ my_missing_packages }} not installed
              and installation disabled. {{ _action }}
          vars:
            _action: "{{ bsd_dns_sanity_fatal | ternary('End play.', 'End host.') }}"

        - name: "Sanity: End play."
          ansible.builtin.meta: end_play
          when: bsd_dns_sanity_fatal | bool

        - name: "Sanity: End host."
          ansible.builtin.meta: end_host

    - name: "Sanity: Debug required packages installed bsd_dns_debug={{ bsd_dns_debug }}"
      ansible.builtin.debug:
        msg: "[OK]  Required packages installed."
      when: bsd_dns_debug | bool

# EOF
