---
- name: "Zones: Stat {{ bsd_named_conf_file }}"
  ansible.builtin.stat:
    path: "{{ bsd_named_conf_file }}"
  register: conf_file

- name: "Zones: Fail when {{ bsd_named_conf_file }} is missing."
  ansible.builtin.fail:
    msg: "[ERROR] {{ bsd_named_conf_file }} is missing. End of play."
  when: not conf_file.stat.exists

- name: "Zones: Set signed zone files for DNSSEC."
  ansible.builtin.set_fact:
    bsd_named_zone_signed: .signed
  when: bsd_named_conf_dnssec_enable|bool

- name: "Zones: Configure master zones in {{ bsd_named_conf_file }}"
  ansible.builtin.include_tasks: fn/conf_master_zone.yml
  loop: "{{ bsd_named_conf_zone }}"
  loop_control:
    label: "{{ item.zone }}"
  when: item.type|lower == 'master'

- name: "Zones: Configure slave zones in {{ bsd_named_conf_file }}"
  ansible.builtin.include_tasks: fn/conf_slave_zone.yml
  loop: "{{ bsd_named_conf_zone }}"
  loop_control:
    label: "{{ item.zone }}"
  when: item.type|lower == 'slave'

- name: "Zones: Configure master reverse zones in {{ bsd_named_conf_file }}"
  ansible.builtin.include_tasks: fn/conf_master_zone_reverse.yml
  loop: "{{ bsd_named_conf_zone }}"
  loop_control:
    label: "{{ item.zone }}"
  when:
    - item.type|lower == 'master'
    - item.reverse

- name: "Zones: Configure slave reverse zones in {{ bsd_named_conf_file }}"
  ansible.builtin.include_tasks: fn/conf_slave_zone_reverse.yml
  loop: "{{ bsd_named_conf_zone }}"
  loop_control:
    label: "{{ item.zone }}"
  when:
    - item.type|lower == 'slave'
    - item.reverse

- name: "Zones: Create zone files"
  ansible.builtin.include_tasks: fn/create_zone_file.yml
  loop: "{{ bsd_named_conf_zone }}"
  loop_control:
    label: "{{ item.zone }}"
  when: item.type|lower == 'master'

- name: "Zones: Create reverse zone files"
  ansible.builtin.include_tasks: fn/create_zone_reverse_file.yml
  loop: "{{ bsd_named_conf_zone }}"
  loop_control:
    label: "{{ item.zone }}"
  when:
    - item.type|lower == 'master'
    - item.reverse

# EOF
