---
# handlers vbotka.freebsd_dns

- name: "enable and start named"
  ansible.builtin.service:
    name: "{{ bsd_named_service }}"
    state: started
    enabled: true

- name: "disable and stop named"
  ansible.builtin.service:
    name: "{{ bsd_named_service }}"
    state: stopped
    enabled: false

- name: "start named"
  ansible.builtin.service:
    name: "{{ bsd_named_service }}"
    state: started

- name: "stop named"
  ansible.builtin.service:
    name: "{{ bsd_named_service }}"
    state: stopped

- name: "restart named"
  ansible.builtin.service:
    name: "{{ bsd_named_service }}"
    state: restarted
  when: bsd_named_enable|bool

- name: "reload named"
  ansible.builtin.service:
    name: "{{ bsd_named_service }}"
    state: reloaded
  when: bsd_named_enable|bool

# TODO: ERROR! 'dict object' has no attribute 'zone'
# - name: sign zones
#  command: >
#    dnssec-signzone -o {{ item.zone }} -k K{{ item.zone }}.KSK
#    /usr/local/etc/namedb/master/{{ item.zone }} K{{ item.zone }}.ZSK.key
#  when: item.changed
#  with_items: bsd_named_zones_created.results

# EOF
...
