---
- block:
    - name: "Zones:conf_master_zone_reverse: Configure master reverse zones {{ item.zone }}"
      ansible.builtin.blockinfile:
        dest: "{{ bsd_named_conf_file }}"
        marker: // *** {mark} ANSIBLE MANAGED BLOCK master {{ item.zone_in }} ***
        insertafter: EOF
        owner: "{{ bsd_named_conf_owner }}"
        group: "{{ bsd_named_conf_group }}"
        mode: "{{ bsd_named_conf_mode }}"
        block: "{{ lookup('template', 'block-named-master-zone-reverse.j2') }}"
        validate: "{{ bsd_named_conf_validate }}"
        backup: "{{ bsd_named_backup_conf }}"
      notify: reload named

  rescue:
    - name: "Zones:conf_master_zone_reverse: Validation failed"
      ansible.builtin.fail:
        msg: "[ERROR] Validation: {{ ansible_failed_result }}"

# EOF
