---

- name: "zones:create_zone_file: Create zone file {{ item.zone }}"
  block:
    - name: "zones:create_zone_file: Create zone file {{ item.zone }}"
      ansible.builtin.template:
        src: zone.j2
        dest: "{{ bsd_named_conf_path }}/{{ item.type }}/{{ item.zone }}"
        owner: "{{ bsd_named_conf_owner }}"
        group: "{{ bsd_named_conf_group }}"
        mode: "{{ bsd_named_conf_mode }}"
        validate: "named-checkzone {{ item.zone }} %s"
        backup: "{{ bsd_named_backup_conf }}"
      register: bsd_named_zones_created
      notify: reload named
  rescue:
    - name: "zones:create_zone_file: Validation failed"
      ansible.builtin.fail:
        msg: "Validation error: {{ ansible_failed_result }}"

# EOF
...
